name:                analyzer
version:             0.1.0
github:              "J3RN/analyzer"
license:             BSD3
author:              "Jonathan Arnett"
maintainer:          "jonathan.arnett@protonmail.com"
copyright:           "Apache 2.0"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/J3RN/analyzer#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
- optparse-applicative >= 0.17.0.0
- regex-tdfa ^>= 1.3.2
  
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  analyzer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - analyzer

tests:
  analyzer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - analyzer
